### ISSUE TITLE
[개선] styled component 코드 개선 

### ISSUE THREAD

**Issue by kokocan12** [woowa-techcamp-2022/web-fleamarket-9#264]
**Problem**  
현재 저희가 만든 styled component들 스타일 정보를 상단에 위치시킨 것도 있고, 하단에 위치시킨 것도 있는데
일관성 있게 개선하면 좋을 것 같아요. 
스타일 정보는 아래에 위치하도록 개선하는 방향을 생각하고 있습니다.

**Comment by padosum** [comment]
말씀하신 것처럼 일관성있게 아래에 배치하는 편이 좋아보입니다
