### ISSUE TITLE
[개선] API 호출 함수 분리

### ISSUE THREAD

**Issue by kokocan12** [woowa-techcamp-2022/web-fleamarket-9#267]
**Problem**  
API 호출 시에 axios.get(....) 이런 식으로 호출하는데, api관련 파일을 따로 만들어서 관리하면 좋을 것 같아요. 
각 함수별로 인터페이스를 만드는 것도 버그를 잡는데 도움이 될 것 같습니다.

**Comment by padosum** [comment]
좋습니다! 👍
