### ISSUE TITLE
[개선] PR#262 관련해서.. 상세페이지 이미지 표시 오류 관련.

### ISSUE THREAD

**Issue by kokocan12** [woowa-techcamp-2022/web-fleamarket-9#269]
**Problem** 
#262
escape함수를 통해서 처리된 것은 확인했습니다.
다만 임시방편 같아서, S3에 이미지 업로드 시 올바른 형태의 주소값을 갖도록 하는 것으로 개선하면 좋을 것 같아요.

파일 이름이 한글이 아니여도 동일한 문제가 발생하는 것 같은데.. 짐작 가는 게 없어서
저희가 놓치고 있는 s3 configuration이 있는지도 확인해봐야 할 것 같기도 해요.

저도 한번 확인해보겠습니다.

**Comment by padosum** [comment]
다른 프로젝트를 살펴보니 보통 `new Date()` 를 사용해 현재 날짜를 key 이름으로 사용하는 걸 확인할 수 있었습니다.
그래서 https://github.com/woowa-techcamp-2022/web-fleamarket-9/blob/31fd10b3e8cf75e5c2d8f8c0327f06a4149759ba/server/src/image/image.service.ts#L20-L25
코드에서 중복방지를 위해 `${Date.now() + file.originalname}`; 로 key 이름을 지정했었는데요,
여기 file의 originalname이 문제가 된 것 같습니다.

**Comment by kokocan12** [comment]
좋을 것 같아요! ~_~

**Comment by kokocan12** [comment]
키값 숫자만 들어가게 해서 수정했습니다~
